Add Update methods
kprivalov/RocketsApp pull request #5
Opened 2022-08-22 13:53 UTC by kprivalov

2022-08-23 19:47 UTC, MortyMerr requested changes

2022-08-23 19:47 UTC, MortyMerr commented on RocketsApp/Presentation/View/RocketScreenViewController.swift
> +    func customizePageControl() {
Лучше в самый низ

2022-08-23 19:47 UTC, MortyMerr commented on RocketsApp/Presentation/View/RocketScreenViewController.swift
> +        guard let index = controllers.firstIndex(of: viewController as! RocketCollectionViewController), index - 1 >= 0 else { return nil }
а почему Force cast? Сделай без него

2022-08-23 19:47 UTC, MortyMerr commented on RocketsApp/Presentation/View/RocketScreenViewController.swift
> +        // swiftlint:disable force_cast
Мы чиним предупреждения линтера, а не просто выключаем их

2022-08-24 13:20 UTC, kprivalov commented on RocketsApp/Presentation/View/Cells/SettingsCell.swift
> +    var onSaveSetting: ((String) -> Void)?
У меня в контроле ничего нет кроме строчек для сегментов. Можно как-то в ячейке ассоциировать их с Unit, но кажется, что для ячейки это чересчур

2022-08-24 13:20 UTC, kprivalov commented on RocketsApp/Presentation/View/Cells/SettingsCell.swift
> +    var onUpdateRocketInfo: (() -> Void)?
Тогда мне придется тащить settingsPresenter в RocketScreenViewController и оттуда через все контроллеры передавать настройки, по-моему, не очень красиво

2022-08-24 16:53 UTC, MortyMerr approved these changes

2022-08-24 16:53 UTC, MortyMerr commented on RocketsApp/Presentation/View/Cells/SettingsCell.swift
> +    var onSaveSetting: ((String) -> Void)?
Ок, принимается

2022-08-24 16:53 UTC, MortyMerr commented on RocketsApp/Presentation/View/Cells/SettingsCell.swift
> +    var onUpdateRocketInfo: (() -> Void)?
Ок, принимается

2022-08-29 12:42 UTC, merged