Implement unit tests
kprivalov/RocketsApp pull request #6
Opened 2022-09-05 22:42 UTC by kprivalov

2022-09-06 22:45 UTC, MortyMerr approved these changes

2022-09-06 22:45 UTC, MortyMerr commented on RocketsAppTests/Helpers/getDataFromJson.swift
> +func getDataFromJSON(fileName name: String, bundleName bundle: AnyClass) -> Data {
Сделай экстеншеном к bundle

2022-09-06 22:45 UTC, MortyMerr commented on RocketsAppTests/Tests/LaunchesPresenterTests.swift
> +        sub = LaunchesScreenPresenter(network: Network(session: urlSession))
Отлично

2022-09-12 14:15 UTC, MortyMerr requested changes

2022-09-12 14:15 UTC, MortyMerr commented on RocketsApp/Presentation/Presenter/LaunchesScreenPresenter.swift
> +    init(network: Network = Network(session: URLSession.shared)) {
Здесь можно не указывать сессию. У тебя уже есть параметр по умолчанию с ней

2022-09-12 14:15 UTC, MortyMerr commented on RocketsApp/Presentation/Presenter/RocketScreenPresenter.swift
> +    init(network: Network = Network(session: URLSession.shared), storage: StorageManager = UserDefaultsManager()) {
тоже не нужна сессия

2022-09-12 14:15 UTC, MortyMerr commented on RocketsApp/Presentation/Presenter/SettingsPresenter.swift
> +    private var storage: StorageManager
let

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Extensions/Bundle+getDataFromJSON.swift
> +            fatalError("Cannot parse JSON")
do catch здесь смысла не имеет ты все равно красишь приложение

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Extensions/Bundle+getDataFromJSON.swift
> +            guard let url = self.url(forResource: file, withExtension: "json") else { fatalError("Cannot find JSON")}
можно написать покороче Guard let через запятую и без опциональной даты.
Тут все равно никак ошибку не обработаешь если файла нет. В тестовом таргете это норм

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Mocks/RocketsMock.swift
> +typealias Item = RocketScreenPresenter.Item
Опять disable вместо фикса правил. В глобальное пространство имен класть typealias или переменные считается дурным тоном.
Сделай это в приватном экстеншене к тесту презентера

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Mocks/URLProtocol.swift
> +class MockURLProtocol: URLProtocol {
final

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/LaunchesPresenterTests.swift
> +class LaunchesPresenterTests: XCTestCase {
final. Ну и правила линтера чини)

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/LaunchesPresenterTests.swift
> +    var sub: LaunchesScreenPresenter!
private

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/LaunchesPresenterTests.swift
> +        let urlSession = URLSession.init(configuration: configuration)
зачем `.init`?

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/LaunchesPresenterTests.swift
> +            XCTAssert(launches.count == 2)
На мой взгляд это выглядело бы красивее, если бы был один ассерт на массив целиком

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +            zip(items, rocketsMock).forEach { item, mock in
Этот тест невозможно читать и понимать что в нем происходит. Если бы он перестал работать у меня, я бы его просто выключил 

Идеальный юнит тест это 
// Given
объявление переменных 

// When
одно действие которое мы тестируем, например
let actualResult = getResult

// Then
ассерт
assert(actualResul, expectedResult)


Циклов, ветвлений, вложенных циклов (в три уровня) в тестах быть не должно

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +            default: break
А в случае default ничего не делаем?

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +        let rocketImages = [
А почему четыре картинки?

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +            let imageItem = $0.first?.sections.first?.items.first
А почему проверяем только одну?

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/SettingsPresenterTests.swift
> +        zip(items.indices, items).forEach { index, item in
zip(items.indices, items) == items.enumareted()

2022-09-12 14:15 UTC, MortyMerr commented on RocketsAppTests/Tests/SettingsPresenterTests.swift
> +        XCTAssert(sub.valueFromStorage(key: .height) == .meters)
В тесте слишком много всего происходит, нужно разбить

2022-09-12 17:59 UTC, kprivalov commented on RocketsApp/Presentation/Presenter/SettingsPresenter.swift
> +    private var storage: StorageManager
Не могу сделать константой, там ниже через storage записываю значения

2022-09-12 18:05 UTC, kprivalov commented on RocketsAppTests/Tests/LaunchesPresenterTests.swift
> +            XCTAssert(launches.count == 2)
Сделал отдельной функцией

2022-09-12 18:06 UTC, kprivalov commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +            zip(items, rocketsMock).forEach { item, mock in
Просто вынес в отдельные функции, как уже говорил, из-за UUID в секциях и в айтемах просто проверить два массива не могу

2022-09-12 18:06 UTC, kprivalov commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +            default: break
Добавил XCTFail()

2022-09-12 18:07 UTC, kprivalov commented on RocketsAppTests/Tests/RocketScreenPresenterTests.swift
> +        let rocketImages = [
Этот тест проверяет, что презентер выбрал случайную картинку из массива. Пусть в моке тогда будет две. Немножно поправил его

2022-09-12 18:08 UTC, kprivalov commented on RocketsAppTests/Tests/SettingsPresenterTests.swift
> +        zip(items.indices, items).forEach { index, item in
Тут что-то не понял: как мне сравнить Zip2Sequence и EnumeratedSequence?

2022-09-13 11:59 UTC, MortyMerr commented on RocketsApp/Presentation/Presenter/SettingsPresenter.swift
> +    private var storage: StorageManager
protocol StorageManager: AnyObject {
 ... 
}
не дает сделать константной, потому что ты не ограничил value type

2022-09-13 11:59 UTC, MortyMerr commented on RocketsAppTests/Mocks/RocketsMock.swift
> +typealias Item = RocketScreenPresenter.Item
Отметил как resolved, но не спрятал typealias

2022-09-15 17:12 UTC, merged